[project]
name = "DLS-AutoPe-as"
version = "0.1.0"
description = "Default template for PDM package"
authors = [
    {name = "Thiago de Paula Monteiro", email = "thiagodepaulamonteiro@gmail.com"},
]
dependencies = ["django>=6.0.5", "djangorestframework>=3.17.1", "psycopg2-binary>=2.9.12", "django-cors-headers>=4.9.0", "Pillow>=12.2.0", "python-dotenv>=1.2.2", "django-cloudinary-storage>=0.3.0", "cloudinary>=1.44.2", "django-environ>=0.13.0", "django-filter>=25.2", "djangorestframework-simplejwt>=5.5.1"]
requires-python = ">=3.14"
readme = "README.md"
license = {text = "MIT"}

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"


[tool.pdm]
distribution = true
