# Generated by Django 6.0.6 on 2026-07-04 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='height_cm',
            field=models.DecimalField(decimal_places=1, default=2.0, help_text='Altura (Mínimo 2cm)', max_digits=5),
        ),
        migrations.AddField(
            model_name='product',
            name='length_cm',
            field=models.DecimalField(decimal_places=1, default=16.0, help_text='Comprimento (Mínimo 16cm)', max_digits=5),
        ),
        migrations.AddField(
            model_name='product',
            name='width_cm',
            field=models.DecimalField(decimal_places=1, default=11.0, help_text='Largura (Mínimo 11cm)', max_digits=5),
        ),
    ]
